ARG BASE_IMAGE
FROM ${BASE_IMAGE}

VOLUME /tmp

RUN mkdir -p /opt/ema && chmod 777 /opt/ema && mkdir -p /go/bin && chmod 777 /go/bin
WORKDIR /opt/ema

ARG GITHASH
ARG GITBRANCH
ARG BUILD_TIMESTAMP

ENV GITHASH="${GITHASH}" \
    GITBRANCH="${GITBRANCH}" \
    BUILD_TIMESTAMP="${BUILD_TIMESTAMP}"

ENV GOPATH /go
ENV PATH /go/bin:$PATH

ARG JAR_FILE
ADD ${JAR_FILE} app.jar

# Do not update, this is the latest MPL-licensed Terraform version
ADD terraform_1.5.5_linux_amd64.tar.gz /go/bin
ADD terraform-provider-solacebroker_0.9.0_linux_amd64.tar.gz /go/bin/

COPY .terraformrc /root/.terraformrc


ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /opt/ema/app.jar --spring.config.location=file:/config/ema.yml"]
