package com.solace.maas.ep.event.management.agent.scanManager.rest;

import com.solace.maas.ep.event.management.agent.scanManager.model.DataCollectionFileDTO;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestParam;

public interface DataCollectionFileController {

    @Operation(
            summary = "Retrieves the details about scan files",
            description = "Use this API to retrieve the details about the files generated by a scan request.",
            responses = {
                    @ApiResponse(
                            responseCode = "200",
                            description = "Details about the scan files have been retrieved successfully."
                    )
            }
    )
    ResponseEntity<Page<DataCollectionFileDTO>> list(@RequestParam("scanId") String scanId, Pageable pageable);
}
